img: /home/nzlov/.config/hypr/wallpaper.jpg
tmpls:
  - t: /home/nzlov/.nzlovdotfile/config/qt6ct/qt.tmpl
    o: /home/nzlov/.config/qt6ct/colors/dt.conf
  - t: /home/nzlov/.nzlovdotfile/config/wofi/wofi.tmpl
    o: /home/nzlov/.nzlovdotfile/config/wofi/style.css
  - t: /home/nzlov/.nzlovdotfile/config/waybar/waybar.tmpl
    o: /home/nzlov/.nzlovdotfile/config/waybar/style.css
    e: killall -SIGUSR2 waybar
